### PR TITLE
Shannon entropy

### LINKED ISSUE #13: Add option to use Shannon Entropy
Currently we use the simplest possible entropy metric - linear entropy from 0 (for zero modules) to N (for all modules).

For some rulesets this produces worlds that are very hard to collapse to a deterministic state. This is because all modules are treated equally, even if some modules are more picky as to what their neighbors can be than others.

For Shannon Entropy we assign a weight for every module. Because we construct the rules directly and do not scan exemplary data, the weight of a module will be determined by its frequency in the ruleset, and not in the sample data.

Biasing the slot choice with weighted entropy should mean that slots containing the more picky modules are observed with a higher priority.

### PR DESCRIPTION
**Pull request by yanchith**
Fixes #13 

I will post some exemplary runs on the Mondieu data set soon.

### CODE REVIEW

**Comment by yanchith** [comment]
So these are the results for various seeds in the Mondieu ruleset. As we can see, Shannon entropy is not doing very well either. Might be a mistake in my implementation, or we could try more rulesets.

```
Seed | Attempts Linear | Attempts Shannon
-----------------------------------------
   0 |           1000+ |            572
   1 |            105  |            994
   2 |            764  |           1000+
   3 |            735  |            162
   5 |            436  |           1000+
   8 |           1000+ |           1000+
  13 |           1000+ |            565
  21 |            305  |            971
  34 |            162  |           1000+
  55 |           1000+ |            995
  ```

**Comment by yanchith** [comment]
Oh, so when I try without the initial state, the ruleset is suddenly very easy to solve.

**Comment by janper** [comment]
> Oh, so when I try without the initial state, the ruleset is suddenly very easy to solve.

bit of course. the elements connect mostly in the Z direction (everything else is indifferent) and there is a hole in the middle of the world. also only certain lents are allowed to be on top and bottom. 
anything that is outside the envelope is `out`.
so indeed the solution is easy without the hole and with anything allowed on top and bottom ;)

**Comment by yanchith** [comment]
> so indeed the solution is easy without the hole and with anything allowed on top and bottom ;)

Now that you say this, this makes perfect sense. We shouldn't have been expecting any improvement here. What makes this specific Mondieu world hard to solve is its shape. And the way we compute weights is not informed by the world shape at all.

A couple of thoughts on this:

- To measure if this is better, we should be using simple, nonrestrictive worlds with potentially difficult rules. Do we have any projects like that?
- We should think, if there is a **useful** way of computing weights such that it takes the world into account. If we already had an already solved world, we could use that, but that is a chicken & egg problem.

**Pull request merged**
