### PR TITLE
Masks

### PR DESCRIPTION
**Pull request by yanchith**
@janper

This adds two things:

- The masks features we talked about: See `wfc_world_state_slot_mask_set` and `Features::MASKED_SLOTS` (`0x04`). If the mask is true, the slot is ignored.. maybe this is unintuitive?

- `wfc_world_state_init_ex`. It is like `wfc_world_state_init`, but you can set initial values for slots (fully zeroed vs fully unobserved), weights (just a number that will be copied everywhere), and masks. It should simplify your initialization code slightly.

I didn't have time to test this at all, so please do test and let me know if you find any problems. If all goes well, I can make a new release out of this for you.

I still need to benchmark this. It adds a condition to an existing branch in hot code. It should be easily predictable, but who knows.

Fixes:
#28
#18

### CODE REVIEW

**Comment by janper** [comment]
Thank you!
I'll test it but it requires quite some work on my side, too.

>  If the mask is true, the slot is ignored.. maybe this is unintuitive?

Yes, this is counterintuitive. I'll test it this way but for the release I prefer it the other way around. Or is there any reason/convention to keep it this way?

> `wfc_world_state_init_ex`

Learnt from Microsoft? :)

**Comment by janper** [comment]
Could we have something like `uint32_t wfc_feature_masked_slots();`?

**Comment by yanchith** [comment]
Yeah, I forgot to add it. Will do.

**Comment by janper** [comment]
I'm getting an exception. 

image

**Comment by yanchith** [comment]
Does the regular init work? You are sending an integer for a weight.

**Comment by janper** [comment]
> Does the regular init work? You are sending an integer for a weight.

I've removed the regular init. i'll try to specify that the numbers are uints

**Comment by janper** [comment]
```C#
            [DllImport("monoceros-wfc-0.5.0-debug.dll", CallingConvention = CallingConvention.StdCall)]
            internal static extern unsafe WfcWorldStateInitResult wfc_world_state_init_ex(IntPtr* wfc_world_state_handle_ptr,
                                                                                          AdjacencyRule* adjacency_rules_ptr,
                                                                                          UIntPtr adjacency_rules_len,
                                                                                          ushort world_x,
                                                                                          ushort world_y,
                                                                                          ushort world_z,
                                                                                          uint features,
                                                                                          uint featuresslot_init_value,
                                                                                          float slot_module_weight_init_value,
                                                                                          uint slot_mask_init_value);
```

**Comment by yanchith** [comment]
Hopefully brought it up to speed. Merging.

**Pull request merged**
